- name: docker
  hosts: all
  tags:
    - bootstrap
    - docker
  vars:
    - docker_packages:
        - name: docker-ce
        - name: docker-compose
    - docker_packages_state: present
    # TODO: change to stable once docker supports bionic
    - docker_apt_release_channel: edge
    - docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
  tasks:
    - name: "docker | Configure dependencies"
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      become: yes
      with_items:
        - name: docker
          state: absent
        - name: docker-engine
          state: absent
        - name: docker.io
          state: absent
        - name: apt-transport-https
          state: present
        - name: ca-certificates
          state: present

    - name: "docker | Configure apt key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: "{{ docker_packages_state }}"
      become: yes

    - name: "docker | Configure repository"
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        filename: docker
        state: present
        update_cache: yes
      become: yes

    - name: "docker | Configure"
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(docker_packages_state) }}"
        autoremove: yes
      with_items: "{{ docker_packages }}"
      become: yes

    - name: "docker | Ensure configuration directory is present"
      file:
        path: /etc/systemd/system/docker.service.d/
        state: directory
      become: yes

    - name: "docker | Configure remote API"
      copy:
        content: |+
          # https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
        dest: /etc/systemd/system/docker.service.d/override.conf
      become: yes
      notify: Restart docker

    - name: "docker | Ensure current user is in the docker group"
      user:
        name: "{{ ansible_user_id }}"
        groups:
          - docker
      become: yes

  handlers:
    - name: "docker | Restart docker.service"
      systemd:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('restarted') }}"
        daemon_reload: "{{ item.daemon_reload | default('yes') }}"
      with_items:
        - name: docker.service
          daemon_reload: yes
      listen: Restart docker
      become: yes
