- name: nvidia
  hosts: all
  gather_facts: yes
  tags:
    - bootstrap
    - nvidia
  vars:
    # TOOD: find a better place to put this
    # - cudnn_deb_url: /mnt/pccfs/not_backed_up/provisioning/resources/libcudnn7_7.1.2.21-1+cuda9.1_amd64.deb
    - cudnn_deb_url: /mnt/pccfs/not_backed_up/provisioning/resources/libcudnn7_7.0.5.15-1+cuda9.1_amd64.deb
    - nvidia_packages_state: present
    - nvidia_packages:
        - name: nvidia-driver-390
        - name: nvidia-cuda-toolkit
  tasks:
    - name: "nvidia | Configure ppa:graphics-drivers apt repository"
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        filename: "graphics-drivers-ubuntu-ppa-{{ ansible_distribution_release }}"
        state: "{{ nvidia_packages_state }}"
      become: yes

    # - name: "nvidia | Remove unecessary cuda repository key"
    #   apt_key:
    #     id: F796ECB0
    #     state: absent
    #   become: yes

    - name: "nvidia | Configure nvidia driver and cuda"
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(nvidia_packages_state) }}"
        autoremove: yes
        install_recommends: yes
        update_cache: yes
      with_items: "{{ nvidia_packages }}"
      become: yes
      notify: Reboot host

    - name: "nvidia | Configure cudnn"
      apt:
        deb: "{{ cudnn_deb_url }}"
        state: "{{ nvidia_packages_state }}"
        autoremove: yes
        install_recommends: yes
      become: yes

  handlers:
    - name: "nvidia | Reboot host"
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: yes
      listen: Reboot host
      become: yes

    - name: "nvidia | Wait for host to reboot"
      wait_for_connection:
        delay: 3
      listen: Reboot host
      become: no
