- name: python
  hosts: all
  tags:
    - bootstrap
    - python3
    - python
  vars:
    - packages_state: present
    - packages:
        - name: python-dev
          state: "{{ packages_state }}"
        - name: python-pip
          state: "{{ packages_state }}"
        - name: python3-dev
          state: "{{ packages_state }}"
        - name: python3-pip
          state: "{{ packages_state }}"
    - pip2_packages:
        - name: numpy
        - name: tqdm
        - name: tensorflow-gpu
        - name: tensorflow-tensorboard
    - pip3_packages: "{{ pip2_packages + [{'name': 'git+https://github.com/BYU-PCCL/hyperdrive.git'}] }}"
  tasks:
    - name: python | Configure
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        autoremove: yes
      with_items: "{{ packages }}"
      become: yes

    - name: python | Configure pip2
      pip:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        executable: pip2
      with_items: "{{ pip2_packages }}"
      become: yes

    - name: python | Configure pip3
      pip:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        executable: pip3
      with_items: "{{ pip3_packages }}"
      become: yes
