- name: python
  hosts: all
  tags:
    - bootstrap
    - python3
    - python
  vars:
    - python_packages:
        - python-dev
        - python-pip
        - python-setuptools
        - python-virtualenv
        - python-wheel
        - python3-dev
        - python3-pip
        - python3-setuptools
        - python3-virtualenv
        - python3-wheel
        - libopencv-gpu-dev
    - python_pip3_packages:
        # TODO: figure out cuda version automatically
        - http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl
        # - hyperdrive
        - jupyter
        - matplotlib
        - numpy
        - opencv-python
        - pandas
        - pillow
        - pygame
        - scikit-image
        - scipy
        - sklearn
        - tensorflow-gpu
        - tensorflow-tensorboard
        - torchvision
        - tqdm
    - python_packages_state: present
    - python_pip3_packages_state: "{{ python_packages_state }}"

  tasks:
    - include_tasks: apt.yml apt_packages_state="{{ python_packages_state }}"

    - name: "python | Configure"
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(python_packages_state) }}"
      with_items: "{{ python_packages }}"
      become: yes

    - name: "python | Configure pip3"
      pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(python_pip3_packages_state) }}"
        executable: pip3
      with_items: "{{ python_pip3_packages }}"
      become: yes
