- name: python
  hosts: all
  tags:
    - bootstrap
    - python3
    - python
  vars:
    - packages_state: present
    - packages:
        - python-dev
        - python-pip
        - python-virtualenv
        - python-setuptools
        - python3-wheel
        - python3-dev
        - python3-pip
        - python3-virtualenv
        - python3-setuptools
        - python3-wheel
    - pip3_packages:
        - jupyter
        - matplotlib
        - numpy
        - pandas
        - pillow
        - pygame
        - scikit-image
        - scipy
        - sklearn
        - tensorflow-gpu
        - tensorflow-tensorboard
        # TODO: figure out cuda version automatically
        - http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl
        - torchvision
        - tqdm
#        - hyperdrive
  tasks:
    - name: python | Configure
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(packages_state) }}"
        autoremove: yes
      with_items: "{{ packages }}"
      become: yes

    - name: python | Configure pip3
      pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(packages_state) }}"
        executable: pip3
      with_items: "{{ pip3_packages }}"
      become: yes
