- name: ubuntu 
  hosts: all
  tags:
    - bootstrap
    - ubuntu
  vars:
    - ubuntu_packages:
        - build-essential
        - curl
        - exfat-fuse
        - exfat-utils
        - git
        - nfs-common
        - openssl
        - wget
    - ubuntu_packages_state: present
    - ubuntu_swappiness: 5
  tasks:
    - include_tasks: apt.yml apt_packages_state="{{ ubuntu_packages_state }}"

    - name: "ubuntu | Configure packages"
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(ubuntu_packages_state) }}"
        autoremove: yes
      with_items: "{{ ubuntu_packages }}"
      become: yes

    - name: "ubuntu | Configure swappiness"
      sysctl:
        name: vm.swappiness
        value: "{{ ubuntu_swappiness }}"
        state: present
      become: yes

    - name: "ubuntu | Ensure incorrect mount pccfs is absent"
      mount:
        path: /mnt/pccfs/
        src: pccfs:/mnt/mainpccfs/mainpccfs_ds1
        fstype: nfs
        opts: auto
        state: absent
      become: yes

    - name: "ubuntu | Mount pccfs"
      mount:
        path: /mnt/pccfs/
        src: pccfs:/mnt/mainpccfs/mainpccfs_ds1
        fstype: nfs
        state: mounted
      become: yes

    - name: "ubuntu | Disable annoying networking message"
      lineinfile:
        path: /etc/default/avahi-daemon
        line: AVAHI_DAEMON_DETECT_LOCAL=0
        regexp: AVAHI_DAEMON_DETECT_LOCAL
      become: yes
