- name: ubuntu
  hosts: all
  tags:
    - bootstrap
    - ubuntu
  vars:
    - ubuntu_packages:
        - build-essential
        - curl
        - exfat-fuse
        - exfat-utils
        - git
        - nfs-common
        - openssl
        - wget
        # - name: account-*
        #   state: absent
        - name: aisleriot
          state: absent
        - name: brltty
          state: absent
        - name: colord
          state: absent
        - name: deja-dup*
          state: absent
        - name: duplicity
          state: absent
        - name: empathy*
          state: absent
        - name: evolution-data-server-online-accounts
          state: absent
        - name: example-content
          state: absent
        - name: gnome-accessibility-themes
          state: absent
        - name: gnome-contacts
          state: absent
        - name: gnome-mahjongg
          state: absent
        - name: gnome-mines
          state: absent
        - name: gnome-orca
          state: absent
        - name: gnome-screensaver
          state: absent
        - name: gnome-sudoku
          state: absent
        - name: gnome-video-effects
          state: absent
        - name: gnomine
          state: absent
        - name: landscape-common
          state: absent
        - name: libsane
          state: absent
        - name: libsane-common
          state: absent
        - name: mcp-account-manager-uoa
          state: absent
        # - name: libreoffice*
        #   state: absent
        #   # libreoffice API
        # - name: python3-uno
        #   state: absent
        - name: rhythmbox*
          state: absent
        - name: sane-utils
          state: absent
        - name: shotwell*
          state: absent
        - name: telepathy*
          state: absent
        - name: thunderbird*
          state: absent
        - name: totem*
          state: absent
        # - name: unity-*
        #   state: absent
    - ubuntu_packages_state: present
    - ubuntu_swappiness: 5
  tasks:
    - include_tasks: apt.yml apt_packages_state="{{ ubuntu_packages_state }}"

    - name: "ubuntu | Configure packages"
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(ubuntu_packages_state) }}"
        autoremove: yes
        purge: yes
      with_items: "{{ ubuntu_packages }}"
      become: yes

    - name: "ubuntu | Configure swappiness"
      sysctl:
        name: vm.swappiness
        value: "{{ ubuntu_swappiness }}"
        state: present
      become: yes

    - name: "ubuntu | Mount pccfs"
      mount:
        path: /mnt/pccfs
        src: pccfs:/mnt/mainpccfs/mainpccfs_ds1
        fstype: nfs
        opts: auto
        state: mounted
      become: yes

    - name: "ubuntu | Disable annoying networking message"
      lineinfile:
        path: /etc/default/avahi-daemon
        line: AVAHI_DAEMON_DETECT_LOCAL=0
        regexp: AVAHI_DAEMON_DETECT_LOCAL
      become: yes
