- name: ubuntu
  hosts: all
  tags:
    - bootstrap
    - ubuntu
  vars:
    - ubuntu_packages:
        - name: build-essential
          state: present
        - name: curl
          state: present
        - name: exfat-fuse
          state: present
        - name: exfat-utils
          state: present
        - name: git
          state: present
        - name: nfs-common
          state: present
        - name: wget
          state: present
        - name: brltty
          state: absent
        - name: gnome-accessibility-themes
          state: absent
    - ubuntu_packages_state: present
    - ubuntu_swappiness: 5
  tasks:
    - include_tasks: apt.yml apt_packages_state="{{ ubuntu_packages_state }}"


    - name: "ubuntu | Configure packages"
      apt:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default(ubuntu_packages_state) }}"
        autoremove: yes
        purge: yes
      with_items: "{{ ubuntu_packages }}"
      become: yes

    - name: "ubuntu | Mount pccfs"
      mount:
        path: /mnt/pccfs
        src: pccfs:/mnt/mainpccfs/mainpccfs_ds1
        fstype: nfs
        opts: auto,_netdev
        state: mounted
      become: yes
